HWPTAG_BEGIN = 0x10
HWPTAG_PARA_HEADER = HWPTAG_BEGIN + 50
HWPTAG_PARA_TEXT = HWPTAG_BEGIN + 51
HWPTAG_PARA_CHAR_SHAPE = HWPTAG_BEGIN + 52
HWPTAG_PARA_LINE_SEG = HWPTAG_BEGIN + 53
HWPTAG_PARA_RANGE_TAG = HWPTAG_BEGIN + 54
HWPTAG_CTRL_HEADER = HWPTAG_BEGIN + 55
HWPTAG_LIST_HEADER = HWPTAG_BEGIN + 56
HWPTAG_PAGE_DEF = HWPTAG_BEGIN + 57
HWPTAG_FOOTNOTE_SHAPE = HWPTAG_BEGIN + 58
HWPTAG_PAGE_BORDER_FILL = HWPTAG_BEGIN + 59
HWPTAG_SHAPE_COMPONENT = HWPTAG_BEGIN + 60
HWPTAG_TABLE = HWPTAG_BEGIN + 61
HWPTAG_SHAPE_COMPONENT_LINE = HWPTAG_BEGIN + 62
HWPTAG_SHAPE_COMPONENT_RECTANGLE = HWPTAG_BEGIN + 63
HWPTAG_SHAPE_COMPONENT_ELLIPSE = HWPTAG_BEGIN + 64
HWPTAG_SHAPE_COMPONENT_ARC = HWPTAG_BEGIN + 65
HWPTAG_SHAPE_COMPONENT_POLYGON = HWPTAG_BEGIN + 66
HWPTAG_SHAPE_COMPONENT_CURVE = HWPTAG_BEGIN + 67
HWPTAG_SHAPE_COMPONENT_OLE = HWPTAG_BEGIN + 68
HWPTAG_SHAPE_COMPONENT_PICTURE = HWPTAG_BEGIN + 69
HWPTAG_SHAPE_COMPONENT_CONTAINER = HWPTAG_BEGIN + 70
HWPTAG_CTRL_DATA = HWPTAG_BEGIN + 71
HWPTAG_EQEDIT = HWPTAG_BEGIN + 72
RESERVED = HWPTAG_BEGIN + 73
HWPTAG_SHAPE_COMPONENT_TEXTART = HWPTAG_BEGIN + 74
HWPTAG_FORM_OBJECT = HWPTAG_BEGIN + 75
HWPTAG_MEMO_SHAPE = HWPTAG_BEGIN + 76
HWPTAG_MEMO_LIST = HWPTAG_BEGIN + 77
HWPTAG_CHART_DATA = HWPTAG_BEGIN + 79
HWPTAG_VIDEO_DATA = HWPTAG_BEGIN + 82
HWPTAG_SHAPE_COMPONENT_UNKNOWN = HWPTAG_BEGIN + 99


def is_main(tag_id):
    return HWPTAG_PARA_HEADER <= tag_id <= HWPTAG_MEMO_LIST or \
           tag_id in [HWPTAG_CHART_DATA, HWPTAG_VIDEO_DATA, HWPTAG_SHAPE_COMPONENT_UNKNOWN]